# Generated by Django 4.2.30 on 2026-09-23 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCyberneticsDataIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('base_url', models.CharField(max_length=2048)),
                ('api_token_encrypted', models.TextField()),
                ('token_hint', models.CharField(blank=True, default='', max_length=16)),
                ('token_fingerprint', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('unauthorized', 'Unauthorized'), ('forbidden', 'Forbidden'), ('unreachable', 'Unreachable'), ('error', 'Error'), ('', 'Never verified')], default='', max_length=32)),
                ('last_verified_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project Cybernetics Data Integration',
                'verbose_name_plural': 'Project Cybernetics Data Integrations',
                'db_table': 'project_cybernetics_data_integrations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueCyberneticsRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('space_id', models.CharField(blank=True, default='', max_length=64)),
                ('base_id', models.CharField(max_length=64)),
                ('table_id', models.CharField(max_length=64)),
                ('record_id', models.CharField(max_length=64)),
                ('view_id', models.CharField(blank=True, default='', max_length=64)),
                ('record_name', models.CharField(blank=True, default='', max_length=512)),
                ('base_name', models.CharField(blank=True, default='', max_length=255)),
                ('table_name', models.CharField(blank=True, default='', max_length=255)),
                ('primary_field_id', models.CharField(blank=True, default='', max_length=64)),
                ('preview', models.JSONField(default=dict)),
                ('source_url', models.CharField(blank=True, default='', max_length=2048)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('missing', 'Missing'), ('forbidden', 'Forbidden')], default='ok', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_cybernetics_records', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Cybernetics Record',
                'verbose_name_plural': 'Issue Cybernetics Records',
                'db_table': 'issue_cybernetics_records',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='projectcyberneticsdataintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project',), name='project_cybernetics_data_unique_project_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcyberneticsdataintegration',
            unique_together={('project', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='issuecyberneticsrecord',
            index=models.Index(fields=['project', 'table_id', 'record_id'], name='icr_project_table_record_idx'),
        ),
        migrations.AddConstraint(
            model_name='issuecyberneticsrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'table_id', 'record_id'), name='issue_cybernetics_record_unique_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='issuecyberneticsrecord',
            unique_together={('issue', 'table_id', 'record_id', 'deleted_at')},
        ),
    ]
