# Generated by Django 4.2.30 on 2026-10-06 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_cybernetics_data_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAgent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=48)),
                ('role_title', models.CharField(blank=True, default='', max_length=255)),
                ('logo_props', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, default='', max_length=280)),
                ('profile_md', models.TextField(blank=True, default='')),
                ('goal_md', models.TextField(blank=True, default='')),
                ('how_it_works_md', models.TextField(blank=True, default='')),
                ('instructions_md', models.TextField(blank=True, default='')),
                ('workflow', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('runtime_hints', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=16)),
                ('accept_assignments', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('definition_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('bot_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Agent',
                'verbose_name_plural': 'Workspace Agents',
                'db_table': 'workspace_agents',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAgentRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('definition', models.JSONField(default=dict)),
                ('definition_hash', models.CharField(max_length=64)),
                ('change_note', models.CharField(blank=True, default='', max_length=500)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='db.workspaceagent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_revisions', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Agent Revision',
                'verbose_name_plural': 'Workspace Agent Revisions',
                'db_table': 'workspace_agent_revisions',
                'ordering': ('-version',),
            },
        ),
        migrations.AddConstraint(
            model_name='workspaceagentrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('agent', 'version'), name='workspace_agent_revision_unique_agent_version_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceagentrevision',
            unique_together={('agent', 'version', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='workspaceagent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'handle'), name='workspace_agent_unique_workspace_handle_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceagent',
            unique_together={('workspace', 'handle', 'deleted_at')},
        ),
    ]
