# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

ERROR_CODES = {
    # issues
    "INVALID_ARCHIVE_STATE_GROUP": 4091,
    "INVALID_ISSUE_DATES": 4100,
    "INVALID_ISSUE_START_DATE": 4101,
    "INVALID_ISSUE_TARGET_DATE": 4102,
    # pages
    "PAGE_LOCKED": 4701,
    "PAGE_ARCHIVED": 4702,
    # cybernetics data
    "CYBERNETICS_NOT_CONFIGURED": 4801,
    "CYBERNETICS_TOKEN_UNREADABLE": 4802,
    "CYBERNETICS_TOKEN_REQUIRED": 4803,
    "CYBERNETICS_UNAUTHORIZED": 4804,
    "CYBERNETICS_FORBIDDEN": 4805,
    "CYBERNETICS_NOT_FOUND": 4806,
    "CYBERNETICS_BAD_REQUEST": 4807,
    "CYBERNETICS_RATE_LIMITED": 4808,
    "CYBERNETICS_UNREACHABLE": 4809,
    "CYBERNETICS_VERIFICATION_FAILED": 4810,
    "CYBERNETICS_ATTACH_FAILED": 4811,
    "CYBERNETICS_ERROR": 4812,
}
